### ISSUE TITLE
Use the correct python way when checking for empty/non-empty lists

### ISSUE THREAD

**Issue by c3ho** [sonechca/Dead_Link_Checker#2]
https://github.com/sonechca/Dead_Link_Checker/blob/1b0fa5cc311847e30d3b13d5e75edda526c0f7bd/DLChecker.py#L59-L63

You can actually switch it to 
```
if links:
  //code

if dead_links:
 //code
```
I was actually curious about this and looked it up: https://stackoverflow.com/questions/53513/how-do-i-check-if-a-list-is-empty

**Comment by sonechca** [comment]
Thank you for replying to me. I fixed this code. I am studying Python now so I am not used to using this yet.
Therefore, I used another programming language's style coding
